# Run example:
# sudo env ANSIBLE_NOCOWS=1 ansible-playbook --skip-tags firefox x1yoga.yml
---
- hosts: localhost
  connection: local
  become: true
  roles:
    - display
    - common
    - packages
