---
- name: Packages | Update Cache
  tags: [extras,packages,packages]
  apt:
    update_cache: yes
- name: Packages | Install Official Packages
  tags: [extras,packages,packages]
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - chkrootkit
    - clamtk
    - git
    - gparted
    - hddtemp
    - hdparm
    - rkhunter
    - screen
    - smartmontools
- name: Packages | Remove Unwanted Packages
  tags: [extras,packages,packages]
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - hexchat
