# sudo env ANSIBLE_NOCOWS=1 ansible-playbook --tags virtualbox x1yoga.yml
---
- name: VirtualBox | Add repository
  tags: [extras,packages,virtualbox]
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    filename: virtualbox
- name: VirtualBox | Add repository key
  tags: [extras,packages,virtualbox]
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
- name: VirtualBox | Remove old versions
  tags: [extras,packages,virtualbox]
  package:
    name: "{{ item }}"
    state: absent
    update_cache: no
  with_items:
    - virtualbox
    - virtualbox-dkms
    - virtualbox-guest-utils
- name: VirtualBox | Install package
  tags: [extras,packages,virtualbox]
  package:
    name: virtualbox-5.2
    state: latest
    update_cache: yes
  register: vbox
- name: VirtualBox | Find guest additions
  tags: [extras,packages,virtualbox]
  shell: wget -O - https://www.virtualbox.org/wiki/Downloads | grep Oracle_VM_VirtualBox_Extension_Pack | sed -n 's/.*<a class="ext-link" href="\([^"]*\)".*/\1/p'
  register: extpack_url
  when: vbox.changed
- name: VirtualBox | Get guest additions filename
  tags: [extras,packages,virtualbox]
  shell: "basename {{extpack_url.stdout}}"
  register: extpack_filename
  when: vbox.changed
- name: VirtualBox | Download guest additions
  tags: [extras,packages,virtualbox]
  get_url:
    url: "{{extpack_url.stdout}}"
    dest: "/tmp/{{extpack_filename.stdout}}"
  when: vbox.changed
- name: VirtualBox | Install guest additions
  tags: [extras,packages,virtualbox]
  shell: "echo y | vboxmanage extpack install --replace /tmp/{{extpack_filename.stdout}}"
  when: vbox.changed
