# WARNING! This is EDGE, sometimes this causes your computer to no longer boot.
# Only for pro's. Use tag 'hwe' to force this.
---
- name: Packages | Install Official Packages
  tags: [never,hwe]
  package:
    name: "{{ item }}"
    state: latest
    install_recommends: yes
  with_items:
    - linux-generic-hwe-16.04-edge
    - xserver-xorg-hwe-16.04
